apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicetest-api-email
  labels:
    app: microservicetest-api-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicetest-api-email
  template:
    metadata:
      labels:
        app: microservicetest-api-email
    spec:
      containers:
      - name: microservicetest-api-email
        image: ricki9/microservicetest.api.email
        imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-microservicetest-api-email 
spec:
  type: NodePort 
  selector:
    app: microservicetest-api-email
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 80
    targetPort: 80


